### PR TITLE
Fixing a problem on the parachute deployment; Changing a bit how the chute ability is handled.

### PR DESCRIPTION
**Pull request by Lisias**
Hi.

I found a problem on the code - if the Tourist has the JetPack ability, the `KourageousTouristsAddOn.OnEvaStart` ends prematurely, and the parachutes are not triggered!

Additionally, I implemented the "SkyDive" ability, so you don't need to hardcode the Tourist Level.

Cheers!

### CODE REVIEW

**Review by whale2 — COMMENTED** [review]
Thanks for the PR.
But wait, the idea was that no training is required for skydiving - that would need bringing the tourists to the space first, which kinda looks like overkill...

**Comment by Lisias** [comment]
Oh, that! Oukey, fixing it in a couple minutes.

**Comment by Lisias** [comment]
Done!

I want to customize the abilities to only allow SkyDive on level 1 on my game, and move up the bodies other than Kerbin to level 2 - so you would be allowed to SkyDive **before** going to space - I think I just forgot I was not editing my customized CFG... :) 

What gave me the idea was the commented out code checking the level of the Tourist, what would allow it to skydive only on level 1 up.

**Comment by Lisias** [comment]
I was thinking... Astronauts have skydiving training before going to space, not tourists!

Tourists will pay the ticket, get strapped into some capsule and then launched into a suborbital flight (Virgin Galactic or Blue Origin style) way before needing some heavy duty astronaut training.

I'm seeing pictures of the interior of SpaceShipTwo from Virgin, and no way PAX will handle parachutes there. No skydiving training needed.

**Comment by Lisias** [comment]
No helmets neither. Found this article about the Virgin Galactic spacesuits for tourists...

https://www.space.com/virgin-galactic-unveils-under-armour-spacesuits-spaceshiptwo.html

**Comment by Lisias** [comment]
Also, from [KSP wiki](https://wiki.kerbalspaceprogram.com/wiki/Experience):

> At level 1, all kerbals gain a personal parachute, except for pilots who have it directly at level 0.

So, even by the game perspective, it makes sense to have some restriction on allowing level 0 Tourists to sky dive - except to see that message about "missing something", of course! =D

**Pull request closed without merging**
