### PR TITLE
Fixed the issue of taking a photo not working

### PR DESCRIPTION
**Pull request by takoss**
Since Application.CaptureScreenshot was deprecated in favour of ScreenCapture.CaptureScreenshot, taking a photo gave an exception and didn't allow to complete the "take a photo ..." mission parameter.

### CODE REVIEW

**Comment by whale2** [comment]
Hi. Thanks for the PR, I think I'll prepare a release with it. Actually, I tried to add skydiving contracts after 1.4 got released and bumped into some issues. Now I feel like I can try making it again.

**Comment by takoss** [comment]
No problem, fixed it for my own use and thought there's no reason not to notify you, since others have probably had the same problem. Also thanks for developing the mod! :)

**Comment by whale2** [comment]
Oh, sorry. That code is the latest release, should have closed this myself.

**Comment by takoss** [comment]
Yeah no worries. Thanks for updating the mod! :)

**Pull request closed without merging**
